/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package banking1;

import java.util.ArrayList;
import java.util.Iterator;

public class App {


    public static void main(String[] args) {



        }



    }

